export const interfaceProperties = {
  titulo: {
    nome_sistema: 'Agide Base',
    fazer_login: 'Fazer Login',
    criar_conta: 'Criar Conta',
    menu: 'Menu',
    meus_dados: 'Meus Dados',
    configuracoes: 'Configurações',
    selecione_perfil: 'Selecione um perfil para continuar',
    recuperar_senha: 'Recuperar Senha',
    informe_seu_email_ou_cpf: 'Informe seu e-mail ou Cpf para redefinição de senha.',
    informe_seu_email_redefinir_senha: 'Informe seu e-mail para redefinir sua senha.',
    seja_bem_vindo: 'Seja bem-vindo!',
    bem_vindo_de_volta: 'Bem-vindo(a) de volta!',
    redefinir_senha: 'Redefinir Senha',
    informe_uma_nova_senha_acesso_sua_conta: 'Informe uma nova senha de acesso à sua conta.',
    codigo_verificacao: 'Código de Verificação',
    campanhas: 'Campanhas',
    campanha: 'Campanha',
    incluir: 'Incluir',
    banners: 'Banners',
    banner: 'Banner',
    perguntas: 'Perguntas',
    pergunta: 'Pergunta',
    questionarios: 'Questionários',
    questionario: 'Questionário',
    manter_perfis: 'Manter Perfil',
    manter_menu: 'Manter Menu',
    perfil: 'Perfil',
    resposta: 'Resposta',
    editar: 'Editar',
    usuarios: 'Usuários',
    criar_senha: 'Cadastrar senha.',
  },
  label: {
    email: 'E-mail',
    senha: 'Senha',
    login: 'Login',
    esqueceu_senha: 'Esqueceu a Senha?',
    entrar: 'Entrar',
    sair: 'Sair',
    cadastrar: 'Cadastrar',
    fazer_login: 'Fazer Login',
    criar_conta: 'Criar Conta',
    meus_dados: 'Meus Dados',
    configuracoes: 'Configurações',
    alterar: 'Alterar',
    id: 'Id',
    usuario: 'Usuário',
    salvar: 'Salvar',
    perfil: 'Perfil',
    selecionar: 'Selecionar',
    acessar_com_outra_conta: 'Acessar com outra conta',
    recuperar: 'Recuperar',
    cpf: 'Cpf',
    enviar_link_recuperacao: 'Enviar link de recuperação',
    voltar_ao_login: 'Voltar ao Login',
    tema_dark: 'Tema Dark',
    acesse_sua_conta_agora: 'Acesse sua conta agora.',
    crie_uma_conta_acessar_nosso_site: 'Crie uma conta para acessar o nosso site.',
    redefinir_senha: 'Redefinir Senha',
    nova_senha: 'Nova Senha',
    confirme_nova_senha: 'Confirme a Nova Senha',
    codigo_verificacao: 'Código de Verificação',
    verificar: 'Verificar',
    nao_possui_uma_conta: 'Não possui uma conta?',
    ja_possui_uma_conta: 'Já possui uma conta?',
    codigo: 'Código',
    nome: 'Nome',
    descricao: 'Descrição',
    ativo: 'Ativo',
    inicio: 'Início',
    fim: 'Fim',
    acoes: 'Ações',
    editar: 'Editar',
    excluir: 'Excluir',
    campanha: 'Campanha',
    sim: 'Sim',
    nao: 'Não',
    cancelar: 'Cancelar',
    incluir: 'Incluir',
    banner: 'Banner',
    tipo_banner: 'Tipo de banner',
    html: 'Html',
    url: 'Url',
    link_imagem: 'Link da imagem',
    required: 'Required',
    tipo_resposta: 'Tipo de Resposta',
    criado_em: 'Criado em',
    atualizado_em: 'Atualizado em',
    pergunta: 'Pergunta',
    obrigatoria: 'Obrigatória',
    resposta: 'Resposta',
    opcoes_resposta: 'Opções de resposta',
    opcao: 'Opção',
    filtrar: 'Filtrar',
    questionario: 'Questionário',
    obrigatorio: 'Obrigatório',
    manter_perfis: 'Manter Perfil',
    escolher_arquivo: 'Escolher arquivo',
    imagem: 'Imagem',
    inserir_link: 'Inserir link',
    proxima: 'Próxima',
    anterior: 'Anterior',
    pular: 'Pular',
    manter_menu: 'Manter Menu',
    menu: 'Menu',
    revisar_respostas: 'Revisar Respostas',
    refazer_questionario: 'Refazer Questionário',
    confirmar_respostas: 'Confirmar Respostas',
    icone: 'Ícone',
    edicao: 'Edição',
    usuarios: 'Usuários',
    reenviar_token: 'Reenviar Token',
    confirme_senha: 'Confirme a sua Senha',
  },
  mensagem: {
    informe_sua_senha: 'Informe sua senha.',
    informe_seu_email: 'Informe seu e-mail.',
    informe_email_valido: 'Informe um e-mail válido.',
    informe_seu_cpf: 'Informe seu Cpf',
    informe_seu_nome: 'Informe seu Nome',
    informe_cpf_valido: 'Informe um Cpf válido.',
    ja_possui_cadastro: 'Já possui cadastro?',
    selecione_um_perfil: 'Selecione um perfil.',
    informe_codigo_enviado_email: 'Por favor, informe o código de 6 dígitos enviado para o e-mail',
    informe_seu_email_link_recuperacao_senha: 'Informe o e-mail cadastrado para enviarmos um link de recuperação de senha.',
    excluido_com_sucesso: 'excluído(a) com sucesso!',
    salvo_com_sucesso: 'salvo(a) com sucesso!',
    atualizado_com_sucesso: 'atualizado(a) com sucesso!',
    tem_certeza_que_deseja_excluir: 'Tem certeza que deseja excluir',
    nenhum_item_encontrado: 'Nenhum item encontrado.',
    nenhum_dado_corresponde_filtro: 'Nenhum dado corresponde ao filtro',
    pergunta_desativada_vinculada_questionario: 'A pergunta foi desativada porque já foi vinculada a um questionário e, portanto, não pode ser excluída.',
    questionario_finalizado_com_sucesso: 'Questionário finalizado com sucesso!',
  },
};
